import { createContext, useContext, useMemo } from "react";

const ENGLISH_TRANSLATIONS = {
  "Beranda": "Home",
  "Koleksi Buku": "Book Collection",
  "Semua": "All",
  "Katalog API": "API Catalog",
  "Favorit": "Favorites",
  "Tentang": "About",
  "Masuk": "Sign In",
  "Keluar": "Sign Out",
  "Setting": "Setting",
  "Akun": "Account",
  "Akun AksaraHub": "AksaraHub Account",
  "Akun Aktif": "Active Account",
  "Masuk ke AksaraHub": "Sign in to AksaraHub",
  "Masuk untuk melanjutkan perjalanan membaca.": "Sign in to continue your reading journey.",
  "Simpan buku favorit, kelola profil pembaca, dan jelajahi katalog dengan pengalaman yang lebih personal.": "Save favorite books, manage your reader profile, and explore the catalog with a more personal experience.",
  "Nama": "Name",
  "Nama kamu": "Your name",
  "Foto Profil": "Profile Photo",
  "pengguna": "user",
  "Pengguna": "User",
  "URL foto, opsional": "Photo URL, optional",
  "Peran Akun": "Account Role",
  "Masukkan password": "Enter password",
  "Email dan password perlu diisi dulu, ya.": "Please fill in your email and password first.",
  "Selamat datang": "Welcome",
  "Sudah keluar": "Signed out",
  "Sesi akunmu ditutup dengan aman.": "Your account session has been closed safely.",
  "Edit Profil": "Edit Profile",
  "Profil Akun": "Account Profile",
  "Keamanan Akun": "Account Security",
  "Preferensi": "Preferences",
  "Bahasa": "Language",
  "Tema": "Theme",
  "Genre Favorit": "Favorite Genres",
  "Detail Profil": "Profile Details",
  "Detail profilmu sudah diperbarui.": "Your profile details have been updated.",
  "Nama lengkap": "Full name",
  "Nama Tampilan": "Display Name",
  "Nama yang ingin ditampilkan": "Name shown in your profile",
  "Foto profil aktif": "Active profile photo",
  "Foto profil dipakai untuk identitas akunmu.": "Your profile photo is used for your account identity.",
  "Tempel URL foto profil": "Paste profile photo URL",
  "Kosongkan untuk memakai avatar inisial.": "Leave it empty to use your initials.",
  "Simpan Profil": "Save Profile",
  "Hapus Foto": "Remove Photo",
  "Password": "Password",
  "Sudah diatur": "Already set",
  "Ganti password": "Change password",
  "Password saat ini": "Current password",
  "Password baru": "New password",
  "Konfirmasi password baru": "Confirm new password",
  "Masukkan password saat ini": "Enter current password",
  "Masukkan password baru": "Enter new password",
  "Ulangi password baru": "Repeat new password",
  "Simpan password": "Save password",
  "Password berhasil diperbarui": "Password updated successfully",
  "Password akun lokal kamu sudah diganti.": "Your local account password has been changed.",
  "Password belum diubah": "Password has not been changed",
  "Isi password baru dulu, ya.": "Please enter a new password first.",
  "Password baru minimal 6 karakter.": "The new password must be at least 6 characters.",
  "Password baru dan konfirmasi password harus sama.": "The new password and confirmation must match.",
  "Password saat ini belum cocok.": "The current password does not match yet.",
  "Password yang kamu masukkan belum cocok.": "The password you entered does not match.",
  "Password belum diatur. Buat password baru untuk akun ini.": "No password is set yet. Create a new password for this account.",
  "Tutup Setting": "Close Setting",
  "Tutup Edit Profil": "Close Edit Profile",
  "Kelola bahasa, tema, dan katalog": "Manage language, theme, and catalog",
  "Kelola preferensi akun dan katalog": "Manage account and catalog preferences",
  "Pengaturan Akun": "Account Settings",
  "Buka Edit Profil": "Open Edit Profile",
  "Buka halaman profil": "Open profile page",
  "Profil": "Profile",
  "Bahasa diperbarui": "Language updated",
  "Pilihan bahasa sudah disimpan.": "Your language choice has been saved.",
  "Light": "Light",
  "Dark": "Dark",
  "Tema tampilan": "Display theme",
  "Preferensi Aplikasi": "App Preferences",
  "Preferensi Katalog": "Catalog Preferences",
  "Tampilan Katalog": "Catalog View",
  "Topik Bawaan": "Default Topic",
  "Mode Tampilan": "View Mode",
  "Ketersediaan": "Availability",
  "Simpan Preferensi": "Save Preferences",
  "Simpan Genre": "Save Genres",
  "Preferensi Bacaan": "Reading Preferences",
  "Data Lokal": "Local Data",
  "Avatar": "Avatar",
  "Avatar profil aktif": "Active profile avatar",
  "Menggunakan avatar inisial": "Using initials avatar",
  "Notifikasi toast": "Toast notifications",
  "Aktif": "Enabled",
  "Nonaktif": "Disabled",
  "Tampilkan notifikasi singkat saat ada perubahan.": "Show short notifications when changes happen.",
  "Notifikasi toast diperbarui": "Toast notifications updated",
  "Notifikasi singkat akan tetap ditampilkan.": "Short notifications will keep appearing.",
  "Notifikasi singkat disembunyikan dari aplikasi.": "Short notifications are hidden from the app.",
  "Jumlah buku per halaman": "Books per page",
  "Atur tampilan katalog yang paling nyaman untuk membaca.": "Choose the catalog layout that feels most comfortable for reading.",
  "Tentukan berapa banyak buku yang tampil di setiap halaman katalog.": "Set how many books appear on each catalog page.",
  "Pilih urutan bawaan saat katalog pertama kali dibuka.": "Choose the default order when the catalog is first opened.",
  "Batas genre tercapai": "Genre limit reached",
  "Pilih maksimal 4 genre favorit.": "Choose up to 4 favorite genres.",
  "Genre favorit tersimpan": "Favorite genres saved",
  "Rekomendasi dapat memakai pilihan genre ini.": "Recommendations can use these genre choices.",
  "Reset Data Lokal": "Reset Local Data",
  "Favorit dan preferensi katalog tersimpan di perangkat ini.": "Favorites and catalog preferences are stored on this device.",
  "Preferensi katalog tersimpan": "Catalog preferences saved",
  "Katalog akan memakai pilihan ini sebagai bawaan.": "The catalog will use these choices as defaults.",
  "Data lokal direset": "Local data reset",
  "Favorit dan preferensi katalog lokal sudah dibersihkan.": "Local favorites and catalog preferences have been cleared.",
  "Hapus favorit": "Clear favorites",
  "Rak favorit akan dikosongkan dari perangkat ini.": "Your favorites shelf will be cleared from this device.",
  "Reset pengaturan": "Reset settings",
  "Bahasa, tema, preferensi katalog, dan genre favorit akan kembali ke bawaan.": "Language, theme, catalog preferences, and favorite genres will return to their defaults.",
  "Konfirmasi hapus favorit": "Confirm clearing favorites",
  "Konfirmasi reset pengaturan": "Confirm resetting settings",
  "Semua buku favorit lokal akan dihapus dari perangkat ini.": "All local favorite books will be removed from this device.",
  "Semua preferensi aplikasi dan katalog akan kembali ke pengaturan awal.": "All app and catalog preferences will return to their default settings.",
  "Favorit dibersihkan": "Favorites cleared",
  "Semua buku favorit lokal sudah dihapus.": "All local favorite books have been removed.",
  "Pengaturan direset": "Settings reset",
  "Preferensi aplikasi dan katalog dikembalikan ke bawaan.": "App and catalog preferences have been restored to defaults.",
  "Belum dipilih": "Not selected yet",
  "Pilih file gambar untuk foto profil, ya.": "Please choose an image file for your profile photo.",
  "Ukuran foto maksimal 1 MB agar profil tetap ringan.": "Keep the photo under 1 MB so your profile stays light.",
  "Email profil perlu diisi dulu, ya.": "Please fill in your profile email first.",
  "Profil tersimpan": "Profile saved",
  "Preferensi bacamu sudah diperbarui.": "Your reading preferences have been updated.",
  "Foto profil dilepas": "Profile photo removed",
  "Avatar inisial akan dipakai lagi.": "Your initials avatar will be used again.",
  "Menjelajahi katalog dan menyimpan buku favorit.": "Browse the catalog and save favorite books.",
  "Mengatur identitas akun dan kebutuhan pengelolaan koleksi.": "Manage account identity and collection needs.",
  "Digital Library": "Digital Library",
  "Navigasi": "Navigation",
  "Navigasi utama": "Main navigation",
  "Navigasi mobile": "Mobile navigation",
  "Buka menu navigasi": "Open navigation menu",
  "Tutup menu navigasi": "Close navigation menu",
  "Aktifkan light mode": "Switch to light mode",
  "Aktifkan dark mode": "Switch to dark mode",
  "buku favorit": "favorite books",
  "Dibuat untuk para pembaca.": "Made for readers.",
  "Genre Populer": "Popular Genres",
  "Newsletter": "Newsletter",
  "Platform perpustakaan digital untuk menemukan buku lokal dan katalog klasik dari API.": "A digital library platform for discovering local books and classic API catalogs.",
  "Dapatkan rekomendasi buku terbaru langsung di email kamu.": "Get the latest book recommendations in your email.",
  "Email kamu...": "Your email...",
  "Daftar newsletter": "Join newsletter",
  "Terima kasih sudah bergabung": "Thanks for joining",
  "Rekomendasi buku akan mampir ke email kamu.": "Book recommendations will visit your inbox.",
  "Privasi": "Privacy",
  "Syarat": "Terms",
  "Kontak": "Contact",
  "Tersedia": "Available",
  "Dipinjam": "Borrowed",
  "Sedang dipinjam": "Currently borrowed",
  "Lihat Detail": "View Details",
  "Simpan ke Favorit": "Save to Favorites",
  "Hapus dari Favorit": "Remove from Favorites",
  "Hapus": "Remove",
  "Favorit disimpan": "Saved to favorites",
  "Dihapus dari favorit": "Removed from favorites",
  "Rak favoritmu sudah diperbarui.": "Your favorites shelf has been updated.",
  "Judul belum tersedia": "Title unavailable",
  "Penulis belum tercatat": "Author not recorded yet",
  "Rating belum tercatat": "Rating not recorded yet",
  "Detail buku": "Book details",
  "Tutup detail buku": "Close book details",
  "Tutup": "Close",
  "Informasi Buku": "Book Information",
  "Penulis": "Author",
  "Tahun Terbit": "Publication Year",
  "Jumlah Halaman": "Page Count",
  "hal": "pages",
  "Sinopsis": "Synopsis",
  "Sinopsis buku ini belum tersedia dari Open Library.": "This book synopsis is not available from Open Library yet.",
  "Buku dipinjam": "Book borrowed",
  "Buku dikembalikan": "Book returned",
  "masuk ke daftar pinjam.": "has been added to your borrowed list.",
  "sudah kembali.": "has been returned.",
  "Sedang Dipinjam": "Currently Borrowed",
  "Kembalikan Buku": "Return Book",
  "Pinjam Buku": "Borrow Book",
  "Hapus Favorit": "Remove Favorite",
  "Simpan Favorit": "Save Favorite",
  "Cari Filter": "Search Filters",
  "Form pencarian dan filter buku": "Book search and filter form",
  "Gunakan filter di bawah untuk menemukan buku": "Use the filters below to find books",
  "Bersihkan": "Clear",
  "Judul Buku": "Book Title",
  "Cari judul buku...": "Search book title...",
  "Cari judul buku": "Search book title",
  "Nama Penulis": "Author Name",
  "Cari nama penulis...": "Search author name...",
  "Cari nama penulis": "Search author name",
  "Cari penulis...": "Search author...",
  "Urutkan hasil": "Sort results",
  "Pilih topik buku": "Choose a book topic",
  "Form pencarian katalog API": "API catalog search form",
  "Genre": "Genre",
  "Tahun Terbit Minimum": "Minimum Publication Year",
  "Rating Minimum": "Minimum Rating",
  "Filter Tambahan": "Additional Filters",
  "Hanya yang tersedia": "Available only",
  "Unggulan saja": "Featured only",
  "Urutkan": "Sort",
  "Urutan Default": "Default Order",
  "Judul A-Z": "Title A-Z",
  "Judul Z-A": "Title Z-A",
  "Tahun Terbaru": "Newest Year",
  "Tahun Terlama": "Oldest Year",
  "Terapkan Filter": "Apply Filters",
  "Koleksi dibuka lagi": "Collection opened again",
  "Semua buku kembali terlihat.": "All books are visible again.",
  "Filter dibersihkan": "Filters cleared",
  "Koleksi kembali tampil utuh.": "The full collection is back.",
  "Rak Pribadi": "Personal Shelf",
  "Buku Favorit": "Favorite Books",
  "Buku": "Book",
  "Rak favorit masih kosong": "Your favorites shelf is still empty",
  "Simpan buku dari beranda atau katalog untuk mulai menyusun rak kecilmu.": "Save books from home or the catalog to start building your small shelf.",
  "Jelajahi Buku": "Explore Books",
  "Buku Pilihan Minggu Ini": "This Week's Pick",
  "oleh": "by",
  "Lihat Koleksi": "View Collection",
  "Total Koleksi": "Total Collection",
  "Pilihan Editor": "Editor's Pick",
  "Buku Unggulan": "Featured Books",
  "Paling Direkomendasikan": "Most Recommended",
  "Koleksi belum siap": "Collection is not ready yet",
  "Sebentar lagi daftar bukunya akan tampil di sini.": "The book list will appear here shortly.",
  "Deskripsi buku ini belum hadir dari katalog Open Library.": "This book description is not available from the Open Library catalog yet.",
  "Deskripsi pendeknya belum tersedia dari Open Library.": "A short description is not available from Open Library yet.",
  "Semua Buku": "All Books",
  "Menampilkan": "Showing",
  "dari": "of",
  "buku": "books",
  "Belum ada hasil yang cocok": "No matching results yet",
  "Coba kata kunci lain, ubah genre, atau bersihkan filternya.": "Try another keyword, change the genre, or clear the filters.",
  "Bersihkan Filter": "Clear Filters",
  "Cari Buku Populer": "Search Popular Books",
  "Mencari buku populer": "Searching popular books",
  "Sebentar, kami pilihkan yang sedang banyak dicari.": "One moment, we are picking what readers search for often.",
  "Sebelumnya": "Previous",
  "Berikutnya": "Next",
  "Data Langsung dari API": "Live Data from API",
  "Perpustakaan Digital": "Digital Library",
  "Sumber": "Source",
  "Mengambil data...": "Fetching data...",
  "Katalog terhubung": "Catalog connected",
  "Cari": "Search",
  "Reset": "Reset",
  "Hasil API": "API Results",
  "Topik": "Topic",
  "Halaman": "Page",
  "Hasil pencarian untuk": "Search results for",
  "Buku tidak ditemukan": "Book not found",
  "Coba kata kunci lain, pilih topik berbeda, atau bersihkan filter.": "Try another keyword, choose another topic, or clear the filters.",
  "Statistik": "Statistics",
  "Ringkasan Koleksi": "Collection Summary",
  "Total Buku": "Total Books",
  "Buku Tersedia": "Available Books",
  "Buku Dipinjam": "Borrowed Books",
  "Genre Terpopuler": "Most Popular Genre",
  "Belum ada data": "No data yet",
  "Top 5 Rating": "Top 5 Ratings",
  "Rating Tertinggi": "Highest Rated",
  "Rating untuk hasil ini belum tersedia.": "Ratings for these results are not available yet.",
  "Pencarian dibersihkan": "Search cleared",
  "Katalog kembali menampilkan semua buku.": "The catalog is showing all books again.",
  "Sebentar, kami ambilkan pilihan yang ramai dicari.": "One moment, we are fetching popular picks.",
  "Tentang AksaraHub": "About AksaraHub",
  "Terhubung ke Open Library": "Connected to Open Library",
  "Tetap Bisa Dipakai Offline": "Still Usable Offline",
  "Pengguna dapat mencari berdasarkan judul, penulis, genre, tahun, rating, dan status ketersediaan.": "Users can search by title, author, genre, year, rating, and availability status.",
  "Setiap buku bisa dibuka untuk melihat metadata penting seperti penulis, genre, tahun, halaman, dan rating.": "Each book can be opened to view key metadata such as author, genre, year, pages, and rating.",
  "Saring koleksi": "Filter Collection",
  "Panel filter membantu mempersempit daftar buku sesuai kebutuhan pembaca.": "The filter panel helps narrow down books to match the reader's needs.",
  "Pilih buku": "Choose a Book",
  "Kartu buku mengarah ke modal detail untuk melihat informasi sebelum meminjam.": "Book cards open detail modals so readers can review information before borrowing.",
  "Perpustakaan digital untuk mencari, menyaring, dan mengenal koleksi buku dengan cepat.": "A digital library for quickly searching, filtering, and exploring book collections.",
  "AksaraHub dibuat sebagai aplikasi katalog buku berbasis React yang memadukan data Open Library dengan koleksi cadangan lokal. Fokus utamanya adalah pengalaman mencari buku yang sederhana, responsif, dan tetap berjalan saat koneksi API bermasalah.": "AksaraHub is a React-based book catalog that combines Open Library data with local fallback collections. Its focus is a simple, responsive book search experience that keeps working when the API connection has trouble.",
  "Cara memakai AksaraHub": "How to Use AksaraHub",
  "Kategori buku yang tersedia": "Available Book Categories",
  "Genre disesuaikan dengan topik yang umum muncul di Open Library dan koleksi contoh aplikasi, sehingga filter lebih mudah dipahami.": "Genres are matched to common Open Library topics and sample collections, making filters easier to understand.",
  "Platform perpustakaan digital yang merangkum koleksi buku, katalog API, dan fitur favorit dalam satu pengalaman yang ringan.": "A digital library platform that brings book collections, API catalogs, and favorites into one light experience.",
  "Data buku utama diambil dari Open Library Search API, lalu dirapikan agar cocok dengan tampilan katalog.": "Main book data is fetched from the Open Library Search API, then refined for the catalog layout.",
  "Jika API tidak bisa diakses, AksaraHub menampilkan koleksi contoh agar halaman tetap dapat dibuka dan diuji.": "If the API cannot be reached, AksaraHub shows sample books so the page stays usable.",
  "Filter Koleksi": "Collection Filters",
  "Cari berdasarkan judul, penulis, genre, tahun, rating, dan status ketersediaan.": "Search by title, author, genre, year, rating, and availability.",
  "Detail Buku": "Book Details",
  "Buka modal detail untuk membaca sinopsis, metadata, rating, dan status peminjaman.": "Open book details to read synopsis, metadata, rating, and borrowing status.",
  "Alur Penggunaan": "How It Works",
  "Lihat rekomendasi": "View Recommendations",
  "Beranda menampilkan buku unggulan dan koleksi yang sedang tersedia.": "Home shows featured books and available collections.",
  "Jelajahi katalog API": "Explore the API Catalog",
  "Halaman katalog menampilkan daftar buku dari data Open Library yang sudah dimuat aplikasi.": "The catalog page shows books loaded from Open Library data.",
  "Simpan favorit": "Save Favorites",
  "Klik tombol favorit untuk menyimpan buku ke rak pribadi.": "Click the favorite button to save books to your personal shelf.",
  "Genre & Data": "Genres & Data",
  "Open Library Search API": "Open Library Search API",
  "Open Library Covers": "Open Library Covers",
  "Fallback books lokal": "Local fallback books",
  "Buku per pencarian": "Books per search",
  "Genre filter": "Genre filters",
  "Sumber online": "Online source",
  "Responsif": "Responsive",
  "Mode gelap aktif": "Dark mode on",
  "Mode terang aktif": "Light mode on",
  "Tampilan dibuat lebih teduh untuk membaca.": "The interface is softer for reading.",
  "Tampilan kembali cerah dan ringan.": "The interface is bright and light again.",
  "Masuk dulu, ya": "Please sign in first",
  "Setelah login, buku favoritmu bisa disimpan rapi.": "After signing in, your favorite books can be saved neatly.",
  "Open Library sedang sulit dihubungi. Kami tampilkan data contoh dulu, ya.": "Open Library is hard to reach right now. We are showing sample data for the moment.",
  "Data belum bisa dibuka": "Data cannot be opened yet",
  "Coba lagi": "Try again",
  "Menyiapkan data...": "Preparing data...",
  "Sebentar, ya": "One moment, please",
  "Konfirmasi": "Confirmation",
  "Keluar dari akun?": "Sign out of account?",
  "Tutup modal": "Close modal",
  "Sesi": "Session for",
  "akan ditutup. Kamu bisa masuk lagi kapan saja.": "will be closed. You can sign in again anytime.",
  "Batal": "Cancel",
  "Tutup notifikasi": "Close notification",
};

const LanguageContext = createContext({
  language: "Indonesia",
  t: (text) => text,
});

export function translateText(text, language = "Indonesia") {
  if (language !== "English") return text;
  return ENGLISH_TRANSLATIONS[text] || text;
}

export function LanguageProvider({ language = "Indonesia", children }) {
  const value = useMemo(
    () => ({
      language,
      t: (text) => translateText(text, language),
    }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
